[package]
name = "student_datahub"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = {version = "2.2.6", features = ["sqlite", "returning_clauses_for_sqlite_3_35"]}
dotenv = "0.15.0"
chrono = "0.4.39"
colored = "3.0.0"